### ISSUE TITLE
Practica en dll

### ISSUE THREAD

**Issue by MariaC232** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-MariaC232#2]
[Practica librerias.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-MariaC232/files/6352792/Practica.librerias.pdf)

**Comment by IMA-G** [comment]
20 %
la explicación de los pasos es clara y concisa

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado
